[tool.poetry]
name = "transactionapp"
version = "0.1.0"
description = ""
authors = ["Timur Gorashchenko <timyr98239718@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
